### ISSUE TITLE
Picture for Positive Emotion is too big 

### ISSUE THREAD

**Issue by choipaul92** [EmotionCognitionLab/factorial-design-breathing-study#10]
When Positive Emotion is checked as 'true,' the pictures presented are too big. I always have to scroll down to press 'Continue.' One picture in particular (stones on water) has text cut off, and I have to use the horizontal scroll bar to read the entire text.

**Comment by noah10** [comment]
Should be fixed in version 1.0.0. If it looks good please close the issue.

**Comment by choipaul92** [comment]
I completed two 18 minute sessions and the pictures for both now fit on the screen
