### ISSUE TITLE
Update text in setup to match spec

### ISSUE THREAD

**Issue by noah10** [EmotionCognitionLab/factorial-design-breathing-study#14]
The text associated with each of the paced breathing steps in stage 1 (in the Stages/Stage 1: Setup in lab/Pulse measurements section of the specification) has changed to tell people to breathe in through their nose. The app needs to reflect these changes.

**Comment by choipaul92** [comment]
This text has been added but I noticed for the last baseline ( 7s breath ). It only mentions breathe in through your nose but not out through your mouth.

**Comment by noah10** [comment]
If I'm reading this correctly then it matches the spec, which also does not mention breathing out through your mouth. I'm guessing that since this is their third time doing this in the last 8 minutes we didn't feel the need to repeat the bit about breathing out, especially since you can breathe out through your nose or your mouth.
