### ISSUE TITLE
Add greeting text before experimental explanation

### ISSUE THREAD

**Issue by juliana-20** [EmotionCognitionLab/factorial-design-breathing-study#16]
Welcome! Let's begin your first practice.

Add a greeting text before experimental explanation (explanation of coherence score) to provide a welcoming experience for participants.

**Comment by noah10** [comment]
Since this refers to your first practice I assume it should only be shown before the first stage 2 practice and then never again?

**Comment by juliana-20** [comment]
Yes, that is correct. This greeting text would be helpful to add for a more smooth introduction for participants' very first session of the study.

**Comment by noah10** [comment]
Added in version 1.0.1.

**Comment by choipaul92** [comment]
@shaakhini, do you remember seeing a greeting text on Day 1 prior to starting Session 1?

**Comment by choipaul92** [comment]
Ver: 1.0.5.

First Text: 

"Welcome! We're going to do some breathing exercises to familiarize you with the heart rate sensor and software. Please sit comfortably and connect the pulse sensor to your ear."

**Comment by choipaul92** [comment]
Ver: 1.0.5

The instructions have been updated

Note: I cannot close this issue because I am not the author 

![IMG_1437](https://github.com/EmotionCognitionLab/factorial-design-breathing-study/assets/89946691/aabd063c-a148-4def-a923-5ad19d8d84ff)

**Comment by juliana-20** [comment]
Thanks for checking. Let me close this issue.
