### ISSUE TITLE
Earnings display shows wrong columns, information

### ISSUE THREAD

**Issue by choipaul92** [EmotionCognitionLab/factorial-design-breathing-study#18]
Factors: Slow, Standard, Hide HR, Show EmoPic, Hide Audio. Performance

After completing my second 18-minute session, I checked the view > earnings page and noticed that the earnings were incorrect. 

![IMG_1389 2](https://github.com/EmotionCognitionLab/factorial-design-breathing-study/assets/89946691/686b6c0c-af4e-4392-a261-6c8212cb5313)

**Comment by juliana-20** [comment]
I believe my earnings are also not shown accurately. The payment for the second session does not display. However, I noticed that the total amount increased.

**Comment by noah10** [comment]
I accidentally built v1.0.0 with the old earnings display code. This should be fixed in v1.0.1.

**Comment by choipaul92** [comment]
Update: Earnings tab have been updated. While bonuses is updated for Day 2, Breathing sessions for Day 2 is not (this however, can be because it does not include activity from the past two days?).
![IMG_1401](https://github.com/EmotionCognitionLab/factorial-design-breathing-study/assets/89946691/293d0838-f314-49a1-aabd-cceb84ec11ed)

**Comment by noah10** [comment]
That's a separate issue. I'll close this one and open a new one.
