### ISSUE TITLE
2 Different Positive Pictures are shown in 1 session if earnings are viewed 

### ISSUE THREAD

**Issue by choipaul92** [EmotionCognitionLab/factorial-design-breathing-study#19]
Factors: Slow, Standard, Hide HR, Show EmoPic, Hide Audio. Performance

When checking my earnings on the dashboard, my positive picture changes before I start my session (ex: Leaves -> Chest on Hands).

Start the app > Log in > Continue to the Session > Pos Pic #1 > View Earnings > View Daily Trainings > Pos Pic #2 > Start my Session

**Comment by noah10** [comment]
In version 1.0.1 the view earnings menu should be disabled when you're viewing an emotional picture.

**Comment by choipaul92** [comment]
Earnings is disabled after picture is show. 

Note: Two pictures can be shown in 1 session if a participant quits and relaunches the app after seeing the initial photo 

Start the app > Log in > Continue to the Session > Pos Pic #1 > quit > Start the App > Continue to the Session > Pos Pic #2 > Start my Session

**Comment by noah10** [comment]
There's not much we can do about that - it's essentially equivalent to the scenario where the app (or computer) crashes while viewing the image. In none of these scenarios is the image view recorded, so it shouldn't mess up the data.
