### ISSUE TITLE
Update breathing instructions screen

### ISSUE THREAD

**Issue by cho890** [EmotionCognitionLab/factorial-design-breathing-study#21]
Please update the breathing instructions screen with the below image (there are 2 versions for two different screen resolutions discussed previously).  This update is per Paul's message on the project Slack channel on 6/11 and Mara's message on 6/24. 

![Breathing instructions (3600px x 2400px)](https://github.com/EmotionCognitionLab/factorial-design-breathing-study/assets/109320017/a2adf10e-51ab-4bc1-91e7-d270fa6772fb)
![Breathing instructions (1366 x 768 px)](https://github.com/EmotionCognitionLab/factorial-design-breathing-study/assets/109320017/7e2cd3d2-8e93-42d2-9e0b-c965aad2e109)

**Comment by noah10** [comment]
Done in v1.0.2.

**Comment by choipaul92** [comment]
The picture and instructions are updated; however, the bullet points are touching the screen.

![Uploading IMG_1409.jpg…]()

**Comment by noah10** [comment]
In version 1.0.5 the bullets should (hopefully) be further to the right.

**Comment by choipaul92** [comment]
After the update in 1.0.5, the breathing instructions look good!

Note: cannot close this issue because I am not the author of this issue

![IMG_1433](https://github.com/EmotionCognitionLab/factorial-design-breathing-study/assets/89946691/2dd104f2-d10f-480f-a3b9-f7de96d3ce9c)
