### ISSUE TITLE
Change redcap/registration integration

### ISSUE THREAD

**Issue by noah10** [EmotionCognitionLab/factorial-design-breathing-study#25]
We will setup the redcap/registration integration as follows:

1. When the participant completes all of the surveys s/he will click on a link that takes him/her to the registration page. That link will include the participant id from redcap.
2. The researcher guiding the participant will be signed into redcap on a different machine from the one the participant is using. S/he will pull up the participant info and confirm that the name, email and phone shown there are the ones that the participant wants to use for the app. If not, the researcher will make the necessary changes in redcap.
3. The participant will enter their name, email, phone and password (and password confirmation) into the registration page and click the submit button.
4. The next screen will display the name, email address and phone number and ask the participant to have the researcher verify the information and enter a password. There will be two buttons: A back button that takes you back to the previous screen and a submit button. If the researcher enters the correct password and clicks the submit button the rest of the registration flow will proceed as it does today (send a confirmation code to the phone, get the code, etc.). If the researcher enters an invalid password the submit button will not be clickable.

A successful registration will save the participant's redcap id in the app database, allowing us to handle drops.

**Comment by choipaul92** [comment]
Ver: 1.0.5 

Tested yesterday and data was saved both on RedCap & Noah's App 

Note: I cannot close this issue because I am not the author
