### ISSUE TITLE
No bonus message shown when bonus is earned

### ISSUE THREAD

**Issue by choipaul92** [EmotionCognitionLab/factorial-design-breathing-study#26]
After completing two 18-minute sessions with no bonus messages, the earnings tab displays a bonus of $3. 

Date: 6/28/24

**Comment by noah10** [comment]
This should be fixed in v1.0.4.

**Comment by choipaul92** [comment]
Ver: 1.0.5

Checked across 3 days while piloting a new condition. Earnings on the dashboard aligned with earning messages after session.
