### ISSUE TITLE
Minor text edit for error condition text

### ISSUE THREAD

**Issue by maramather** [EmotionCognitionLab/factorial-design-breathing-study#28]
Under 'error conditions' please make the following text change in the instructions:

“No or poor signal detected. Please make sure the device is connected properly and your earlobe is warm. (If it is cold, try rubbing it between your thumb and forefinger to warm it up and get blood flowing to it.)” will be displayed.

replace "it" with "your earlobe" as follows

“No or poor signal detected. Please make sure the device is connected properly and your earlobe is warm. (If your earlobe is cold, try rubbing it between your thumb and forefinger to warm it up and get blood flowing to it.)” will be displayed.

**Comment by noah10** [comment]
This is done in v1.0.5.
