### ISSUE TITLE
Please edit Y axis label

### ISSUE THREAD

**Issue by maramather** [EmotionCognitionLab/factorial-design-breathing-study#29]
For the heart rate biofeedback, the Y axis shows "BPM" which may be an opaque term for participants. Please replace it with "Beats per minute". Please also change the title at the top of the display from "Heart Rate (BPM)" to just read "Heart Rate".

**Comment by choipaul92** [comment]
![Screenshot 2024-07-14 151646](https://github.com/user-attachments/assets/4d943378-f7f9-476b-b717-46a74f989138)

Ver: 1.0.6

The graph now reflects the change. 

Note: I cannot close this issue because I am not the author.
