### ISSUE TITLE
Update display text after participant hits 'Start' to begin breathing session

### ISSUE THREAD

**Issue by cho890** [EmotionCognitionLab/factorial-design-breathing-study#3]
After a participant hits 'Start' to begin a breathing session, the display text in the heart rate graph shows "Calibrating."  Please change this text to say, "Please begin breathing now while following the pacer on the right.”

**Comment by noah10** [comment]
The text (which appears below the heart rate graph) shows "Waiting for pulse signal..." and the pacer doesn't start until we get a pulse signal, so I don't think the proposed text works.

**Comment by cho890** [comment]
Page 17 of the app specs states, "After clicking the start the breath pacer will begin moving immediately and the word “Calibrating” will appear on the heart rate chart. Once we begin receiving data from the heart rate sensor (~10s) the chart will start graphing the participant’s heart rate."  Is this outdated?

**Comment by noah10** [comment]
Good catch! I had totally missed that. If we do that we'll end up with data that reflect a shorter breathing period than planned, since we'll have no data while the sensor is being calibrated. Assigning this to @maramather to see if that's really what we want.

**Comment by maramather** [comment]
Ok, given that the breath pacer is not already in action during calibration, let's just keep it as is.

**Comment by maramather** [comment]
@cho890 would you be able to update the app spec to reflect the current app reality so that no one else runs into this as an issue?

**Comment by cho890** [comment]
The app spec has been updated.
