### ISSUE TITLE
Incomplete Sessions

### ISSUE THREAD

**Issue by shaakhini** [EmotionCognitionLab/factorial-design-breathing-study#30]
I did my first session for Day 3 of the 12th condition and my computer ran out of charge in the middle. When I opened my computer back up, it had me restart the entire 18 minutes. Then, for my second session, it only ran for 8 minutes.

**Comment by noah10** [comment]
That sounds correct. If you do a partial session and time out it will ask you to start a new one. Every time you start a new session it will be 18 minutes long unless giving you 18 minutes would put you over 36 minutes for the day, in which case it will give you the maximum possible to bring you up to 36 minutes.
