### ISSUE TITLE
Remove mention of 'factorial' across the app

### ISSUE THREAD

**Issue by cho890** [EmotionCognitionLab/factorial-design-breathing-study#31]
Please either remove mention of 'factorial' or 'factorial study' or replace with 'breathing' or 'breathing study.'  This will create a consistent, seamless experience for participants, as all recruitment materials describe it as a breathing study.

**Comment by shaakhini** [comment]
I tested the new version and the name is changed to Breathing Study. Note, the older version of the app, named Factorial Design Breathing Study, is still on the desktop. There is a just a new app below it now, labeled Breathing Study.

**Comment by noah10** [comment]
The fact that the old one is still on the desktop is normal. It can be deleted. Sounds like this is all working as expected.
