### ISSUE TITLE
Add sentence to instructions in sound condition

### ISSUE THREAD

**Issue by maramather** [EmotionCognitionLab/factorial-design-breathing-study#32]
As now indicated in the app spec, please add the sentence:

"If you find it helps, you may close your eyes during the sessions and use the sound to guide your breathing." to the instructions for the sound condition.

**Comment by choipaul92** [comment]
![Screenshot 2024-07-18 124700](https://github.com/user-attachments/assets/714271de-3d65-4003-84bc-389c983acc07)

Ver: 1.0.8

Instructions have been updated

**Comment by maramather** [comment]
thanks Paul!
