### ISSUE TITLE
Breathing pacer continued after timer ended in condition 5

### ISSUE THREAD

**Issue by juliana-20** [EmotionCognitionLab/factorial-design-breathing-study#7]
At the end of the 18-minute session, the breathing pacer continued for at least a minute or so. The session ended when the ear sensor was removed and no pulse was detected. That's when the data was saved and uploaded. 

Update - no issues occurred after completing the second round of the 18-minute paced breathing session

**Comment by noah10** [comment]
I'm going to close this since we haven't had any further reports of it. We can re-open it if necessary.
