### ISSUE TITLE
Heart rate data disappears when you click "Heart Rate (bpm)"

### ISSUE THREAD

**Issue by shaakhini** [EmotionCognitionLab/factorial-design-breathing-study#8]
When you click on "Heart Rate (bpm)" which appears as a key above the heart rate data graph, the data disappears from the graph, leaving the participant to view a blank graph instead.

**Comment by choipaul92** [comment]
I tested this and was able to replicate this. I also found out if you click on it again, the data re-appears.

Tested on a random condition: Condition 31.

**Comment by noah10** [comment]
This is fixed in version 0.2.0 of the app. If the fix works for you please go ahead and close this issue.

**Comment by choipaul92** [comment]
Ver: 1.0.5. 

Tested this & the Heart Rate Graph does not disappear if you click on it. 

Note: I cannot close this issue because I am not the author.
